server:
  port: 8080

spring:
  application:
    name: sentiment-analyzer

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true

logging:
  level:
    root: INFO
    com.orkestory: DEBUG
